set(WORLDBUILDER_SRC
    "include/AutoEdgeOutTool.h"
    "include/BaseBuildProps.h"
    "include/BlendEdgeTool.h"
    "include/BlendMaterial.h"
    "include/BorderTool.h"
    "include/BrushTool.h"
    "include/BuildList.h"
    "include/BuildListTool.h"
    "include/CButtonShowColor.h"
    "include/CFixTeamOwnerDialog.h"
    "include/CellWidth.h"
    "include/ContourOptions.h"
    "include/EditCoordParameter.h"
    "include/EditGroup.h"
    "include/EditObjectParameter.h"
    "include/EyedropperTool.h"
    "include/FeatherOptions.h"
    "include/FeatherTool.h"
    "include/FenceOptions.h"
    "include/FenceTool.h"
    "include/FloodFillTool.h"
    "include/GlobalLightOptions.h"
    "include/GroveOptions.h"
    "include/GroveTool.h"
    "include/HandScrollTool.h"
    "include/ImpassableOptions.h"
    "include/LightOptions.h"
    "include/MapPreview.h"
    "include/MapSettings.h"
    "include/MeshMoldOptions.h"
    "include/MeshMoldTool.h"
    "include/MoundOptions.h"
    "include/MoundTool.h"
    "include/MyToolbar.h"
    "include/NewHeightMap.h"
    "include/ObjectOptions.h"
    "include/ObjectPreview.h"
    "include/ObjectTool.h"
    "include/OpenMap.h"
    "include/OptionsPanel.h"
    "include/PickUnitDialog.h"
    "include/PointerTool.h"
    "include/PolygonTool.h"
    "include/RampOptions.h"
    "include/RampTool.h"
    "include/RoadOptions.h"
    "include/RoadTool.h"
    "include/SaveMap.h"
    "include/ScorchOptions.h"
    "include/ScorchTool.h"
    "include/ScriptActionsFalse.h"
    "include/ScriptActionsTrue.h"
    "include/ScriptConditions.h"
    "include/ScriptProperties.h"
    "include/SelectMacrotexture.h"
    "include/ShadowOptions.h"
    "include/SplashScreen.h"
    "include/StdAfx.h"
    "include/TeamBehavior.h"
    "include/TeamGeneric.h"
    "include/TeamIdentity.h"
    "include/TeamReinforcement.h"
    "include/TerrainMaterial.h"
    "include/TerrainModal.h"
    "include/TerrainSwatches.h"
    "include/TileTool.h"
    "include/Tool.h"
    "include/WBFrameWnd.h"
    "include/WBHeightMap.h"
    "include/WBPopupSlider.h"
    "include/WaterOptions.h"
    "include/WaterTool.h"
    "include/WaypointOptions.h"
    "include/WaypointTool.h"
    "include/WorldBuilderDoc.h"
    "include/WorldBuilderView.h"
    "include/addplayerdialog.h"
    "include/brushoptions.h"
    "include/playerlistdlg.h"
    "include/propedit.h"
    "include/teamsdialog.h"
    "src/AutoEdgeOutTool.cpp"
    "src/BaseBuildProps.cpp"
    "src/BlendEdgeTool.cpp"
    "src/BlendMaterial.cpp"
    "src/BorderTool.cpp"
    "src/BrushTool.cpp"
    "src/BuildList.cpp"
    "src/BuildListTool.cpp"
    "src/CButtonShowColor.cpp"
    "src/CFixTeamOwnerDialog.cpp"
    "src/CellWidth.cpp"
    "src/ContourOptions.cpp"
    "src/EditCoordParameter.cpp"
    "src/EditGroup.cpp"
    "src/EditObjectParameter.cpp"
    "src/EyedropperTool.cpp"
    "src/FeatherOptions.cpp"
    "src/FeatherTool.cpp"
    "src/FenceOptions.cpp"
    "src/FenceTool.cpp"
    "src/FloodFillTool.cpp"
    "src/GlobalLightOptions.cpp"
    "src/GroveOptions.cpp"
    "src/GroveTool.cpp"
    "src/HandScrollTool.cpp"
    "src/ImpassableOptions.cpp"
    "src/LightOptions.cpp"
    "src/MapPreview.cpp"
    "src/MapSettings.cpp"
    "src/MeshMoldOptions.cpp"
    "src/MeshMoldTool.cpp"
    "src/MoundOptions.cpp"
    "src/MoundTool.cpp"
    "src/MyToolbar.cpp"
    "src/NewHeightMap.cpp"
    "src/ObjectOptions.cpp"
    "src/ObjectPreview.cpp"
    "src/ObjectTool.cpp"
    "src/OpenMap.cpp"
    "src/OptionsPanel.cpp"
    "src/PickUnitDialog.cpp"
    "src/PointerTool.cpp"
    "src/PolygonTool.cpp"
    "src/RampOptions.cpp"
    "src/RampTool.cpp"
    "src/RoadOptions.cpp"
    "src/RoadTool.cpp"
    "src/SaveMap.cpp"
    "src/ScorchOptions.cpp"
    "src/ScorchTool.cpp"
    "src/ScriptActionsFalse.cpp"
    "src/ScriptActionsTrue.cpp"
    "src/ScriptConditions.cpp"
    "src/ScriptProperties.cpp"
    "src/SelectMacrotexture.cpp"
    "src/ShadowOptions.cpp"
    "src/SplashScreen.cpp"
    "src/StdAfx.cpp"
    "src/TeamBehavior.cpp"
    "src/TeamGeneric.cpp"
    "src/TeamIdentity.cpp"
    "src/TeamReinforcement.cpp"
    "src/TerrainMaterial.cpp"
    "src/TerrainModal.cpp"
    "src/TerrainSwatches.cpp"
    "src/Tool.cpp"
    "src/WBFrameWnd.cpp"
    "src/WBHeightMap.cpp"
    "src/WBPopupSlider.cpp"
    "src/WaterOptions.cpp"
    "src/WaterTool.cpp"
    "src/WaypointOptions.cpp"
    "src/WaypointTool.cpp"
    "src/WorldBuilderView.cpp"
    "src/addplayerdialog.cpp"
    "src/brushoptions.cpp"
    "src/propedit.cpp"
)

add_library(corei_worldbuilder INTERFACE)

target_sources(corei_worldbuilder INTERFACE ${WORLDBUILDER_SRC})

target_include_directories(corei_worldbuilder INTERFACE
    include
)

target_link_libraries(corei_worldbuilder INTERFACE
    core_browserdispatch
    d3d8lib
    imm32
    vfw32
    winmm
)
